spring:
  application:
    name: ircs-migrator
  main:
    web-application-type: none
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DB_URL:jdbc:postgresql://postgres-svc:5432/ircs?connectionTimeZone=UTC}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:}}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

logging:
  level:
    liquibase: INFO
    com.prodigalgal.ircs.migrator: INFO
