-- liquibase formatted sql

-- changeset zzp84:1772700000000-add-search-outbox
CREATE TABLE search_sync_tasks (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   entity_type VARCHAR(50) NOT NULL,
                                   entity_id UUID NOT NULL,
                                   operation VARCHAR(20) NOT NULL,
                                   status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
                                   retry_count INT DEFAULT 0,
                                   created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
                                   next_retry_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

-- 索引优化轮询查询：查找状态为 PENDING 且到期可执行的任务
CREATE INDEX idx_search_sync_poll ON search_sync_tasks (status, next_retry_at)
    WHERE status = 'PENDING';